### ISSUE TITLE
gatttool is depracated

### ISSUE THREAD

**Issue by cgm999** [sercona/Owon-Multimeters#5]
Hi,

I am on archlinux which does not have gatttool in the std package list . Any plans on updating this project to use some other tool or module ? Thank you

**Comment by sercona** [comment]
currently, no immediate plans.

the reason is that that part is a 'hard' part to do properly and gatttool does work and works well for what it is.

I really dont see the need to re-invent what already works.

there are some tools like this dmm tool that are more native python.

but I chose to keep a loose coupling between the bluetooth part and the decoding part (that is the value-add of this application).

I understand that calling a process and scraping its text output is less than ideal.

but you ARE on linux.  you should be able to find a pre-built gatttool or just build one yourself.  arch is source based.

I honestly dont think I can do better than gatttool.  I am not a bluetooth person (very little experience in the BT protocols and devices) and I'd rather have that part worked out and just concentrate on the part that is the DMM serial decode.

to me, this is a little like having a network stack (tcp/ip) and just using it as-is.  I'd never want to re-implement a comms stack that already works.  there would be more bugs and it would gain no new functionality for that effort.

longer term, what I DO want to try - is to move this entirely over to an esp32 and use its bluetooth stack.  then you would not need linux at all; it would be a wifi/restful remote access method rather than a linux cli command being called repeatedly.

I do plan to get to that project but its not on the short term list.

**Comment by cgm999** [comment]
Ok that make sense.. will close this, 10x for feedback!

**Comment by sercona** [comment]
I do hope that eventually this can be moved to an esp32.  it would boot instantly and you can use the $4 chips as web/http front ends and not have to care about linux specifics.

I'm happy to accept help in doing the BT decode on the esp32.  I have a good amount of esp background but I'm not a BT expert and have not touched esp bt code (yet).

so again, volunteers accepted for this task ;)

**Comment by sercona** [comment]
I just added some early beta code that will run ENTIRELY on esp32 !

This will entirely solve any linux gatt issue (lol).
